### ISSUE TITLE
Icons under Scenes tab are not centered

### ISSUE THREAD

**Issue by ckdragons** [kandashi/smol-foundry#4]
The icons that show which scenes are shared with players are appearing below the scene, not center like the icons under the other tabs. Using Foundry 0.8.8 on Forge. I have all 3 smol options all set to 50.
![Untitled](https://user-images.githubusercontent.com/84493092/125900862-ffc18179-bba4-4bb0-9800-9b9d35c3fb4a.png)

**Comment by kandashi** [comment]
That isn't a core foundry function and im afraid adding individual module support itsnt too high on my priority list right now. 
If you can find out which module it is you could make a suggestion to them that they use a percentage in their code rather than a hard number

**Comment by ckdragons** [comment]
Thank you. It would appear to be the fvtt-module-permission-viewer (in case anyone else has this issue). I've sent a note to that developer.
