### ISSUE TITLE
Certain actions cause scenes to revert

### ISSUE THREAD

**Issue by OutlandishVillainy** [kandashi/smol-foundry#6]
Certain things cause scenes to revert back to default size. Here's a video of it happening when you delete a scene, it also happens when you navigate between scenes. The smol-foundry settings will come back on a reload.

![Animation1](https://user-images.githubusercontent.com/93902659/148926056-664c72dc-480f-48a2-8abe-d85f7ccafb21.gif)

**Comment by ckdragons** [comment]
Still happens with the current version installed. Found the bug when I moved a scene within the Scene tab (i.e. reordering my scenes).
![image](https://user-images.githubusercontent.com/84493092/155659349-7a713a5a-4491-4d93-8bfb-433796fd1eac.png)
![image](https://user-images.githubusercontent.com/84493092/155659371-21324aae-3f99-423c-9ff2-2fc36ef884b1.png)
